In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('Netflix_Unclean_Project.xlsx')

In [3]:
df = pd.read_excel('Netflix_Unclean_Project.xlsx')

In [4]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\sadhw\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sadhw\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: C:\Program Files\Python312\python.exe -m pip install --upgrade pip

In [5]:
df = pd.read_excel('Netflix_Unclean_Project.xlsx')
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [6]:
#Check
df.tail

<bound method NDFrame.tail of      Customer_ID   Customer_Name  Age          Title Content_Type  \
0      CUST10927    Customer 927   25     Bridgerton      TV Show
1      CUST10631    Customer 631   38     Bridgerton        Movie
2      CUST10683    Customer 683   40    Money Heist      TV Show
3      CUST10515    Customer 515   44         You         TV Show
4      CUST10366    Customer 366   57    The Witcher  TV Show
...          ...             ...  ...            ...          ...
1008   CUST55545    Customer 515   44         You         TV Show
1009   CUST55546    Customer 366   57    The Witcher  TV Show
1010   CUST55547    Customer 656   42            You        Movie
1011   CUST55548    Customer 657   22     Squid Game      TV Show
1012   CUST55549    Customer 530   61          Elite        Movie

               Genre  Country Subscription_Plan          Device  \
0              Drama    Japan           Premium  Gaming Console
1        Documentary    Japan             Basic          Mobile
2             Sci-Fi   France             Basic          Tablet
3             Action    Spain           Premium  Gaming Console
4             Comedy   Canada           Premium        Smart TV
...              ...      ...               ...             ...
1008          Action    Spain           Premium  Gaming Console
1009          Comedy   Canada           Premium        Smart TV
1010             NaN  Germany             Basic          Mobile
1011     Documentary   Canada           Premium        Smart TV
1012           Drama  Germany          Standard          Tablet

     Payment_Method Account_Status  Join_Date Last_Watch_Date  Watch_Hours  \
0            PayPal         Active 2024-06-20      2024-12-21         28.0
1            PayPal         Active 2024-01-01      2024-08-14          0.0
2        Debit Card         Paused 2024-11-18      2025-10-31         28.9
3       Credit Card         Active 2023-02-21      2023-06-18         27.6
4       Credit Card         Active 2024-01-16      2025-06-09         32.0
...             ...            ...        ...             ...          ...
1008    Credit Card         Active 2023-02-21      2023-06-18         27.6
1009    Credit Card         Active 2024-01-16      2025-06-09         32.0
1010    Credit Card         Paused 2023-10-31      2025-08-10         43.5
1011    Credit Card         Active 2025-05-15      2025-09-11         42.3
1012     Debit Card         Paused 2025-04-08      2026-05-21         19.4

      Monthly_Fee  Movies_Watched  Episodes_Watched  Avg_Rating  \
0             649               5                97         3.6
1             149               5                84         4.5
2             149              16               106         3.8
3             649              10                24         2.6
4             649              10                78         3.2
...           ...             ...               ...         ...
1008          649              10                24         2.6
1009          649              10                78         3.2
1010          149              32                11         4.5
1011          649              19                11         2.8
1012          499              14                91         3.5

      Monthly_Sessions  Download_Count
0                   11               3
1                   22              19
2                   26               3
3                   27               9
4                   15              20
...                ...             ...
1008                27               9
1009                15              20
1010                12               7
1011                12              23
1012                15              23

[1013 rows x 20 columns]>

In [7]:
#Initial Data Exploration
df.shape

(1013, 20)

In [8]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   object
 1   Customer_Name      1013 non-null   object
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   object
 4   Content_Type       1013 non-null   object
 5   Genre              1010 non-null   object
 6   Country            1013 non-null   object
 7   Subscription_Plan  1013 non-null   object
 8   Device             1009 non-null   object
 9   Payment_Method     1008 non-null   object
 10  Account_Status     1013 non-null   object
 11  Join_Date          1013 non-null   datetime64[ns]
 12  Last_Watch_Date    1013 non-null   datetime64[ns]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(10)
memory usage: 158.4+ KB

In [10]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612096,2024-11-27 19:59:45.784797696,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [11]:
#Missing Values

df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [12]:
# Duplicate Records

df.duplicated().sum()

np.int64(5)

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
#Dirty Values - N/A, NULL,blank,spaces

df.replace(
    ['N/A','NULL','',' '],np.nan,inplace=True
)

In [16]:
#Dirty Values - N/A, NULL,blank,spaces

df.replace(
    ['N/A','NULL','',' '],np.nan,inplace=True
)

In [17]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                4
Country              1
Subscription_Plan    0
Device               4
Payment_Method       7
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [18]:
#Extra Spaces Remove

df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [19]:
# Standardize Text

df["Country"] = df["Country"].str.title()

df["Genre"] = df["Genre"].str.title()

df["Subscription_Plan"] = (df["Subscription_Plan"].str.title())

df["Account_Status"] = (df["Account_Status"].str.title())

In [20]:
df['Country'].value_counts()

Country
Spain             109
United States     107
Germany           104
Canada            103
United Kingdom    102
Japan             100
France             98
India              97
South Korea        96
Australia          91
Name: count, dtype: int64

In [21]:
# Numeric Columns

numeric_cols = ['Age', 'Watch_Hours', 
                'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating', 
                'Monthly_Sessions', 'Download_Count']

In [22]:
for col in numeric_cols:
    df[col]=pd.to_numeric(df[col],errors='coerce')

In [23]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008,1008,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,42.097222,2023-12-15 20:42:51.428571392,2024-11-28 00:20:00.000000256,42.449107,435.960317,18.226190,59.766865,3.751984,16.690476,12.448413
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-07 18:00:00,2023-12-25 12:00:00,25.650000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-28 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,54.000000,2024-12-13 00:00:00,2025-11-14 06:00:00,58.100000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.258334,NaN,NaN,24.016448,214.461100,10.099231,34.916046,0.724172,8.287380,7.559714

In [24]:
df = df[(df['Age']>=18)&(df['Age']<=100)]

In [25]:
df['Age'].describe()

count    1003.000000
mean       41.973081
std        13.811906
min        18.000000
25%        30.000000
50%        43.000000
75%        53.500000
max        65.000000
Name: Age, dtype: float64

In [26]:
# Negative Values

df[df['Watch_Hours']<=0]

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
36,CUST10934,Customer 934,56,Lupin,TV Show,Drama,United States,Basic,Mobile,Debit Card,Active,2023-07-28,2024-08-10,0.0,149,29,118,3.2,17,4
61,CUST10430,Customer 430,49,The Witcher,TV Show,Documentary,Canada,Basic,Gaming Console,Debit Card,Active,2025-03-29,2025-05-07,0.0,149,31,90,3.4,20,15
113,CUST10991,Customer 991,40,Money Heist,TV Show,Animation,United States,Standard,Gaming Console,UPI,Active,2022-03-27,2023-02-19,-20.0,499,34,72,3.9,19,16
159,CUST10061,Customer 61,60,Peaky Blinders,TV Show,Documentary,India,Premium,Tablet,Net Banking,Active,2022-01-03,2023-05-29,-2.0,649,29,97,2.6,10,17
174,CUST10111,Customer 111,46,Black Mirror,Movie,Documentary,India,Basic,Smart TV,Net Banking,Active,2023-03-31,2024-04-30,0.0,149,6,47,3.1,12,3
177,CUST10526,Customer 526,38,Lucifer,Movie,Comedy,France,Basic,Laptop,Credit Card,Active,2025-04-29,2026-05-21,0.0,149,15,2,4.9,19,20
180,CUST10545,Customer 545,24,Elite,TV Show,Romance,Spain,Standard,Gaming Console,UPI,Cancelled,2024-04-25,2024-05-12,0.0,499,8,94,4.2,7,25
190,CUST10222,Customer 222,53,Elite,Movie,Romance,South Korea,Standard,Laptop,Net Banking,Cancelled,2022-06-26,2024-03-25,0.0,499,16,59,3.4,17,24
218,CUST10669,Customer 669,25,Bridgerton,Movie,Drama,Canada,Basic,Smart TV,Debit Card,Active,2025-09-10,2026-01-20,0.0,149,14,83,2.9,19,8
225,CUST10050,Customer 50,35,Lucifer,TV Show,Thriller,United States,Standard,Tablet,Debit Card,Active,2024-07-18,2026-01-18,0.0,499,12,24,3.0,17,8
269,CUST10383,Customer 383,57,Dark,Movie,Documentary,Australia,Premium,Gaming Console,UPI,Active,2024-09-16,2024-11-17,0.0,649,19,25,4.5,21,8
287,CUST10722,Customer 722,43,Ozark,Movie,Drama,Japan,Premium,Smart TV,Credit Card,Active,2025-08-07,2025-11-22,0.0,649,5,46,4.0,29,10
303,CUST10443,Customer 443,38,You,Movie,Comedy,Spain,Premium,Mobile,PayPal,Active,2025-09-29,2025-11-30,0.0,649,17,104,3.2,16,2
307,CUST10569,Customer 569,43,Lupin,TV Show,Crime,Australia,Premium,Smart TV,NaN,Paused,2024-12-13,2026-04-29,0.0,649,27,105,2.9,18,4
322,CUST10080,Customer 80,46,Elite,Movie,Romance,United States,Standard,Laptop,Net Banking,Paused,2023-03-21,2025-01-10,0.0,499,23,7,3.5,8,3
432,CUST10286,Customer 286,56,The Queen's Gambit,TV Show,Sci-Fi,United States,Premium,Mobile,Credit Card,Active,2025-06-23,2026-06-22,0.0,649,19,70,3.8,24,3
435,CUST10992,Customer 992,59,Narcos,TV Show,Romance,United Kingdom,Standard,Smart TV,Credit Card,Active,2025-01-23,2026-10-27,0.0,499,28,51,3.6,4,15
443,CUST10576,Customer 576,52,Bridgerton,Movie,Crime,South Korea,Basic,Tablet,Net Banking,Active,2025-09-10,2027-03-11,0.0,149,21,51,4.0,17,0
462,CUST10075,Customer 75,26,Peaky Blinders,TV Show,Horror,Canada,Basic,Laptop,Credit Card,Active,2023-02-16,2024-06-24,0.0,149,19,95,4.7,27,3
485,CUST10397,Customer 397,43,The Umbrella Academy,TV Show,Sci-Fi,India,Premium,Tablet,PayPal,Active,2022-10-05,2023-04-30,0.0,649,30,11,3.1,24,20
514,CUST10016,Customer 16,21,Ozark,TV Show,Comedy,South Korea,Premium,Tablet,Credit Card,Active,2022-07-21,2022-12-12,-8.0,649,28,23,3.2,9,2
526,CUST10432,Customer 432,58,Peaky Blinders,TV Show,Animation,India,Basic,Laptop,Net Banking,Cancelled,2025-11-01,2027-02-25,0.0,149,30,65,4.8,20,23
541,CUST10447,Customer 447,40,Squid Game,TV Show,Documentary,India,Premium,Mobile,Debit Card,Active,2025-01-01,2025-12-16,-12.0,649,6,107,3.6,26,9
544,CUST10237,Customer 237,26,Squid Game,Movie,Romance,India,Premium,Mobile,Credit Card,Active,2023-02-17,2023-07-13,0.0,649,8,108,3.8,13,2
565,CUST10741,Customer 741,25,The Queen's Gambit,TV Show,Documentary,France,Standard,Laptop,Debit Card,Cancelled,2024-10-25,2026-01-05,0.0,499,34,97,3.3,7,14
643,CUST10976,Customer 976,57,Lupin,Movie,Romance,South Korea,Premium,Smart TV,UPI,Active,2023-08-25,2024-01-31,0.0,649,18,3,3.7,28,22
646,CUST10038,Customer 38,22,The Umbrella Academy,TV Show,Romance,Canada,Premium,Smart TV,PayPal,Active,2023-03-15,2024-05-19,0.0,649,25,115,4.4,24,0
652,CUST10709,Customer 709,39,The Queen's Gambit,Movie,Thriller,India,Basic,Gaming Console,Debit Card,Active,2023-09-22,2024-01-27,0.0,149,2,105,2.6,19,9
654,CUST10195,Customer 195,43,Lupin,Movie,Romance,Japan,Standard,Smart TV,Net Banking,Active,2025-06-05,2027-04-26,-5.0,499,20,117,4.0,4,21
699,CUST10263,Customer 263,30,Dark,Movie,Drama,Australia,Premium,Smart TV,Debit Card,Active,2023-09-04,2023-10-01,0.0,649,32,37,3.1,15,12
722,CUST10609,Customer 609,43,Lupin,Movie,Thriller,South Korea,Standard,Tablet,PayPal,Cancelled,2025-04-05,2026-05-16,0.0,499,14,39,3.6,14,18
733,CUST10439,Customer 439,59,You,TV Show,Crime,Spain,Standard,Mobile,Debit Card,Active,2025-06-04,2026-07-10,0.0,499,30,98,4.2,9,23
758,CUST10978,Customer 978,44,Bridgerton,TV Show,Animation,France,Premium,Laptop,Debit Card,Cancelled,2023-01-29,2023-10-26,0.0,649,28,47,3.4,9,10
769,CUST10672,Customer 672,20,Narcos,Movie,Crime,South Korea,Basic,Tablet,Net Banking,Active,2023-05-01,2024-12-27,0.0,149,23,35,2.8,21,13
821,CUST10734,Customer 734,49,Narcos,TV Show,Comedy,Spain,Standard,Smart TV,UPI,Active,2025-05-22,2026-09-16,0.0,499,10,81,3.0,20,1
873,CUST10472,Customer 472,28,You,Movie,Action,Germany,Basic,Tablet,NaN,Active,2022-08-12,2024-05-16,0.0,149,2,37,3.5,23,17
882,CUST10015,Customer 15,33,The Queen's Gambit,TV Show,Thriller,United States,Premium,Mobile,PayPal,Active,2024-08-26,2025-10-21,0.0,649,30,110,4.3,23,20
938,CUST10014,Customer 14,32,The Crown,Movie,Romance,United States,Premium,Gaming Console,Credit Card,Active,2022-05-01,2023-09-11,0.0,649,14,69,2.8,30,18
946,CUST10647,Customer 647,22,The Umbrella Academy,TV Show,Crime,France,Basic,Tablet,Credit Card,Active,2022-07-18,2022-12-03,0.0,149,13,62,3.0,5,14
953,CUST10567,Customer 567,63,Peaky Blinders,Movie,Romance,Spain,Premium,Laptop,Net Banking,Active,2025-03-04,2026-03-26,0.0,649,34,94,3.1,12,16
1006,CUST55543,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19

In [27]:
df[df['Monthly_Fee']<=0]

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
17,CUST10980,Customer 980,63,Peaky Blinders,Movie,Sci-Fi,Spain,Basic,Gaming Console,UPI,Active,2023-12-15,2025-03-08,61.0,-649,32,75,3.6,7,0
379,CUST10074,Customer 74,58,Wednesday,Movie,Crime,Germany,Premium,Mobile,Net Banking,Active,2022-10-08,2023-02-20,81.1,-149,6,116,3.2,25,13
515,CUST10634,Customer 634,63,Stranger Things,Movie,Drama,Australia,Premium,Mobile,Debit Card,Active,2025-04-18,2026-07-01,31.3,-499,16,79,2.7,6,11

In [28]:
# Data Cleaning

df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')
df['Last_Watch_Date'] = pd.to_datetime(df['Last_Watch_Date'], errors='coerce')

In [29]:
# Missing Values Hande

df["Age"].fillna(
    df["Age"].mean(),
    inplace=True
)

df["Watch_Hours"].fillna(
    df["Watch_Hours"].mean(),
    inplace=True
)

df["Monthly_Fee"].fillna(
    df["Monthly_Fee"].mean(),
    inplace=True
)

C:\Users\sadhw\AppData\Local\Temp\ipykernel_33004\1559035612.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(
C:\Users\sadhw\AppData\Local\Temp\ipykernel_33004\1559035612.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Watch_Hours"].fillna(
C:\Users\sadhw\AppData\Local\Temp\ipykernel_33004\1559035612.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Monthly_Fee"].fillna(

In [30]:
# Missing Values Hande

df["Age"] = df["Age"].fillna(
    df["Age"].mean()
)

df["Watch_Hours"] = df["Watch_Hours"].fillna(
    df["Watch_Hours"].mean()
)

df["Monthly_Fee"] = df["Monthly_Fee"].fillna(
    df["Monthly_Fee"].mean()
)

In [31]:
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")
df["Device"] = df["Device"].fillna("Unknown")
df["Genre"] = df["Genre"].fillna("Unknown")

In [32]:
# Feature Engineering

In [33]:
# Customeer Revenue

df["Customer_Revenue"] = (df["Monthly_Fee"] *df["Monthly_Sessions"])

In [34]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3,7139
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19,3278
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3,3874
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9,17523
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20,9735

In [35]:
# Engagement Score

df["Engagement_Score"] = (df["Watch_Hours"] +df["Monthly_Sessions"] +df["Download_Count"])

In [36]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,2024-12-21,28.0,649,5,97,3.6,11,3,7139,42.0
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,2024-08-14,0.0,149,5,84,4.5,22,19,3278,41.0
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,2025-10-31,28.9,149,16,106,3.8,26,3,3874,57.9
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,2023-06-18,27.6,649,10,24,2.6,27,9,17523,63.6
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,2025-06-09,32.0,649,10,78,3.2,15,20,9735,67.0

In [37]:
# Watch Category
bins = [0,20,50,100,np.inf]
label = ['Low', 'Medium', 'High', 'Very High']

df['Watch_Category'] = pd.cut(df['Watch_Hours'], bins=bins, labels=label)

In [38]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,28.0,649,5,97,3.6,11,3,7139,42.0,Medium
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,0.0,149,5,84,4.5,22,19,3278,41.0,NaN
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,28.9,149,16,106,3.8,26,3,3874,57.9,Medium
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,27.6,649,10,24,2.6,27,9,17523,63.6,Medium
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,32.0,649,10,78,3.2,15,20,9735,67.0,Medium

In [39]:
df['Watch_Category'].value_counts()

Watch_Category
Medium       450
High         359
Low          142
Very High     10
Name: count, dtype: int64

In [40]:
# Customer Age Group

bins = [17,25,35,50,100]
label = ['18-25', '26-35', '36-50', '51+']

df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=label)

In [41]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,649,5,97,3.6,11,3,7139,42.0,Medium,18-25
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,149,5,84,4.5,22,19,3278,41.0,NaN,36-50
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,149,16,106,3.8,26,3,3874,57.9,Medium,36-50
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,649,10,24,2.6,27,9,17523,63.6,Medium,36-50
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,649,10,78,3.2,15,20,9735,67.0,Medium,51+

In [42]:
df['Age_Group'].value_counts()

Age_Group
51+      329
36-50    311
26-35    215
18-25    148
Name: count, dtype: int64

In [43]:
# Account Active Flag
df["Active_Flag"] = np.where(df["Account_Status"] = "Active",1,0)

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (340656951.py, line 2)

In [ ]:
# Account Active Flag
df["Active_Flag"] = np.where(df["Account_Status"] = "Active",1,0)

In [ ]:
# Account Active Flag
df["Active_Flag"] = np.where(df["Account_Status"] == "Active",1,0)

In [ ]:
df.head()

In [ ]:
# Final Data Quality Check
df.info()

In [ ]:
df.isnull.sum()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.describe()

In [ ]:
# Clean Excel Export
df.to_csv('Netflix_Clean_Data.csv',index=False)

In [ ]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:root@localhost/netflix_db')

In [ ]:
%pip install sqlalchemy pymysql

In [ ]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:root@localhost/netflix_db')

In [ ]:
with engine.connect() as connection:
    print("Connected successfully!")

In [ ]:
df.to_sql(
    'netflix_customers',
    con = engine
    if_exists = 'replace',
    index=False              
)

In [ ]:
df.to_sql(
    'netflix_customers',
    con = engine,
    if_exists = 'replace',
    index=False              
)

In [44]:
df.to_sql(
    'netflix_customers',
    con = engine,
    if_exists = 'replace',
    index=False              
)

NameError: name 'engine' is not defined

In [45]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,...,649,5,97,3.6,11,3,7139,42.0,Medium,18-25
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,...,149,5,84,4.5,22,19,3278,41.0,NaN,36-50
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,149,16,106,3.8,26,3,3874,57.9,Medium,36-50
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,...,649,10,24,2.6,27,9,17523,63.6,Medium,36-50
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,...,649,10,78,3.2,15,20,9735,67.0,Medium,51+